//! Runs tauri-build. On Windows (MSVC) it also embeds the application manifest
//! through the linker, so that test executables get it too.
//!
//! Tauri links against Common Controls v6 (`TaskDialogIndirect` and others).
//! tauri-build embeds the manifest that selects v6 only into the app executable,
//! so `cargo test` binaries fail to start with STATUS_ENTRYPOINT_NOT_FOUND
//! (tauri-apps/tauri#13419). Passing the manifest to the linker for every target
//! fixes that; tauri-build is told not to embed a second copy.

const MANIFEST: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/windows-app-manifest.xml");

/// Every app command. With an app manifest, Tauri checks app commands against the
/// capabilities, so each one needs its `allow-<command>` permission granted to a window
/// in `capabilities/` (the `ai_*` commands to `main` only). tauri-build writes the
/// permissions to `permissions/autogenerated/` (ignored by git). The `bench_*` commands
/// exist only with the dev-only `bench` feature; their permissions are harmless without it.
const APP_COMMANDS: &[&str] = &[
    "app_info",
    "ai_set_key",
    "ai_has_key",
    "ai_delete_key",
    "ai_fetch",
    "ai_abort",
    "bench_commit_json",
    "bench_commit_binary",
    "bench_patch_stream",
    "bench_ping",
    "bench_ping_async",
    "bench_log",
    "bench_report",
];

fn main() {
    let windows = if is_windows_msvc() {
        println!("cargo:rerun-if-changed={MANIFEST}");
        println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
        println!("cargo:rustc-link-arg=/MANIFESTINPUT:{MANIFEST}");
        tauri_build::WindowsAttributes::new_without_app_manifest()
    } else {
        tauri_build::WindowsAttributes::new()
    };

    let attributes = tauri_build::Attributes::new()
        .windows_attributes(windows)
        .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS));
    if let Err(error) = tauri_build::try_build(attributes) {
        panic!("tauri-build failed: {error:#}");
    }
}

fn is_windows_msvc() -> bool {
    let target_var = |name| std::env::var(name).unwrap_or_default();
    target_var("CARGO_CFG_TARGET_OS") == "windows" && target_var("CARGO_CFG_TARGET_ENV") == "msvc"
}
