// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Returns the product name and version configured in `tauri.conf.json`. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Stores the Claude API key in the OS keychain, replacing any earlier key. */
	aiSetKey: (key: string) => typedError<null, string>(__TAURI_INVOKE("ai_set_key", { key })),
	/**  Whether a Claude API key is stored. */
	aiHasKey: () => typedError<boolean, string>(__TAURI_INVOKE("ai_has_key")),
	/**  Deletes the stored Claude API key, if any. */
	aiDeleteKey: () => typedError<null, string>(__TAURI_INVOKE("ai_delete_key")),
	/**
	 *  Forwards one request to the Claude API with the stored key. `on_event` receives the
	 *  response head first, then the body chunks, then an end, error or aborted marker. The
	 *  command itself resolves when the response is over.
	 */
	aiFetch: (request: ProxyRequest, onEvent: Channel<ProxyEvent>) => typedError<null, string>(__TAURI_INVOKE("ai_fetch", { request, onEvent })),
	/**  Cancels the in-flight request `request_id`. Returns whether there was one. */
	aiAbort: (requestId: string) => __TAURI_INVOKE<boolean>("ai_abort", { requestId }),
};

/* Types */
/**  Name and version of the running application, as shown in the UI. */
export type AppInfo = {
	/**  Product name, e.g. `Typefaced`. */
	name: string,
	/**  Semantic version of the application, e.g. `0.1.0`. */
	version: string,
};

/**
 *  One message on the response channel, in this order: `Head`, any number of `Chunk`s,
 *  then exactly one of `End`, `Error` or `Aborted`. A refused request sends only `Error`.
 */
export type ProxyEvent = 
/**
 *  Status and response headers (without `set-cookie`). The caller's `fetch` can
 *  resolve on this message, before the body arrives.
 */
{ kind: "head"; status: number; headers: ([string, string])[] } | 
/**
 *  The next part of the body as UTF-8 text. A character split across network reads
 *  is sent whole in the later chunk; invalid bytes become U+FFFD.
 */
{ kind: "chunk"; text: string } | 
/**  The body ended normally. */
{ kind: "end" } | 
/**  The request was refused or failed. The message never contains the key. */
{ kind: "error"; message: string } | 
/**  `abort` cancelled the request. */
{ kind: "aborted" };

/**  A request as the webview's `fetch` describes it, before any check. */
export type ProxyRequest = {
	/**  Chosen by the caller (e.g. a UUID); `ai_abort` cancels the request by this ID. */
	requestId: string,
	/**  `GET` or `POST`. */
	method: string,
	/**  Absolute URL, e.g. `https://api.anthropic.com/v1/messages`. */
	url: string,
	/**  Header name and value pairs. */
	headers: ([string, string])[],
	/**  UTF-8 body, if any (the Claude API takes JSON). */
	body: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

