// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Returns the product name and version configured in `tauri.conf.json`. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
};

/* Types */
/**  Name and version of the running application, as shown in the UI. */
export type AppInfo = {
	/**  Product name, e.g. `Typefaced`. */
	name: string,
	/**  Semantic version of the application, e.g. `0.1.0`. */
	version: string,
};

