//! `cargo xtask context check | update`: the `CONTEXT.md` maps. Every folder has a
//! `CONTEXT.md` that names each of its files, the root one links every other one and
//! holds a generated file map, and every Rust file starts with a `//!` comment.
//! This module is pure; `main.rs` lists the files and reads and writes them.

use std::collections::{BTreeMap, BTreeSet};

/// File name of a folder map.
pub const CONTEXT: &str = "CONTEXT.md";

/// Folders that tools read in full, so they must not hold a `CONTEXT.md`. Their
/// subfolders and every folder inside a `*.ufo` package are exempt too.
pub const EXEMPT_DIRS: [&str; 1] = ["apps/desktop/src-tauri/capabilities"];

/// Markers around the generated file map in the root `CONTEXT.md`.
pub const MAP_START: &str = "<!-- file-map:start (generated by `cargo xtask context update`) -->";
pub const MAP_END: &str = "<!-- file-map:end -->";

/// The repository as the checks see it.
pub struct Tree {
    /// Every file, as a `/`-separated path relative to the root.
    pub files: Vec<String>,
    /// Text of every `CONTEXT.md` and `.rs` file, by path.
    pub texts: BTreeMap<String, String>,
}

/// Whether `path` is a folder map.
pub fn is_context(path: &str) -> bool {
    base(path) == CONTEXT
}

/// Whether `dir` (a `/`-separated path, `""` for the root) must not hold a `CONTEXT.md`.
pub fn is_exempt(dir: &str) -> bool {
    dir.split('/').any(|part| part.ends_with(".ufo"))
        || EXEMPT_DIRS.iter().any(|exempt| {
            dir.strip_prefix(exempt)
                .is_some_and(|rest| rest.is_empty() || rest.starts_with('/'))
        })
}

/// All violations of the rules in the module comment.
pub fn violations(tree: &Tree) -> Vec<String> {
    let files: BTreeSet<&str> = tree.files.iter().map(String::as_str).collect();
    let dirs = dirs(&files);
    let text = |path: &str| tree.texts.get(path).map_or("", String::as_str);
    let mut found = folder_problems(&files, &dirs, &text);
    found.extend(file_problems(&files, &text));
    found.extend(link_problems(&files, &dirs, &text));
    found.extend(rust_problems(&files, &text));
    if files.contains(CONTEXT) {
        let root = text(CONTEXT);
        match with_file_map(root, &tree.files) {
            Err(e) => found.push(e),
            Ok(updated) if updated != root => found.push(
                "the file map in CONTEXT.md is out of date: run `cargo xtask context update`"
                    .into(),
            ),
            Ok(_) => {}
        }
    }
    found
}

/// `root_text` with its generated file map replaced by the map of `files`.
pub fn with_file_map(root_text: &str, files: &[String]) -> Result<String, String> {
    let start = root_text.find(MAP_START);
    let end = start.and_then(|start| root_text[start..].find(MAP_END).map(|i| start + i));
    match (start, end) {
        (Some(start), Some(end)) => Ok(format!(
            "{}{MAP_START}\n```text\n{}```\n{}",
            &root_text[..start],
            render(files),
            &root_text[end..]
        )),
        _ => Err(format!(
            "CONTEXT.md has no file map between `{MAP_START}` and `{MAP_END}`"
        )),
    }
}

/// The file map of `files` as a tree, without the `CONTEXT.md` files. Folders come
/// before files; a folder with a single entry is joined with it (`apps/desktop/`).
pub fn render(files: &[String]) -> String {
    let mut root = Node::default();
    for path in files.iter().filter(|path| !is_context(path)) {
        let (dir, file) = path.rsplit_once('/').unwrap_or(("", path));
        let mut node = &mut root;
        for part in dir.split('/').filter(|part| !part.is_empty()) {
            node = node.dirs.entry(part).or_default();
        }
        node.files.insert(file);
    }
    let mut out = String::from(".\n");
    write_children(&root, "", &mut out);
    out
}

#[derive(Default)]
struct Node<'a> {
    dirs: BTreeMap<&'a str, Node<'a>>,
    files: BTreeSet<&'a str>,
}

fn write_children(node: &Node, prefix: &str, out: &mut String) {
    let entries: Vec<(String, Option<&Node>)> = node
        .dirs
        .iter()
        .map(|(name, dir)| label(name, dir))
        .chain(node.files.iter().map(|file| ((*file).to_owned(), None)))
        .collect();
    for (i, (name, child)) in entries.iter().enumerate() {
        let last = i + 1 == entries.len();
        let (branch, indent) = if last {
            ("└── ", "    ")
        } else {
            ("├── ", "│   ")
        };
        out.push_str(&format!("{prefix}{branch}{name}\n"));
        if let Some(child) = child {
            write_children(child, &format!("{prefix}{indent}"), out);
        }
    }
}

/// The label of a folder, joined with its only entry while it has just one.
fn label<'n>(name: &str, mut node: &'n Node<'n>) -> (String, Option<&'n Node<'n>>) {
    let mut name = name.to_owned();
    loop {
        let only_dir = node.dirs.iter().next().filter(|_| node.dirs.len() == 1);
        let only_file = node.files.iter().next().filter(|_| node.files.len() == 1);
        match (
            only_dir,
            only_file,
            node.dirs.is_empty(),
            node.files.is_empty(),
        ) {
            (Some((dir, child)), _, _, true) => {
                name = format!("{name}/{dir}");
                node = child;
            }
            (_, Some(file), true, _) => return (format!("{name}/{file}"), None),
            _ => return (format!("{name}/"), Some(node)),
        }
    }
}

fn base(path: &str) -> &str {
    path.rsplit_once('/').map_or(path, |(_, name)| name)
}

fn parent(path: &str) -> &str {
    path.rsplit_once('/').map_or("", |(dir, _)| dir)
}

fn context_of(dir: &str) -> String {
    if dir.is_empty() {
        CONTEXT.to_owned()
    } else {
        format!("{dir}/{CONTEXT}")
    }
}

/// Whether `text` names `name` as a whole code span, e.g. `` `lib.rs` ``.
fn mentions(text: &str, name: &str) -> bool {
    text.contains(&format!("`{name}`"))
}

/// Every folder that holds a file, its ancestors and the root (`""`).
fn dirs<'a>(files: &BTreeSet<&'a str>) -> BTreeSet<&'a str> {
    let mut dirs = BTreeSet::from([""]);
    for file in files {
        let mut dir = parent(file);
        while dirs.insert(dir) {
            dir = parent(dir);
        }
    }
    dirs
}

fn folder_problems<'a>(
    files: &BTreeSet<&str>,
    dirs: &BTreeSet<&str>,
    text: &impl Fn(&str) -> &'a str,
) -> Vec<String> {
    let root_links: BTreeSet<String> = relative_links(text(CONTEXT))
        .into_iter()
        .filter_map(|target| resolve("", without_anchor(target)))
        .collect();
    let mut found = Vec::new();
    for &dir in dirs {
        let context = context_of(dir);
        let exists = files.contains(context.as_str());
        if is_exempt(dir) {
            if exists {
                found.push(format!(
                    "`{context}` must not exist: tools read every file in that folder"
                ));
            }
            continue;
        }
        if !exists {
            found.push(match dir {
                "" => "the root has no CONTEXT.md".to_owned(),
                _ => format!("`{dir}/` has no CONTEXT.md"),
            });
            continue;
        }
        if dir.is_empty() {
            continue;
        }
        let parent_context = context_of(parent(dir));
        if files.contains(parent_context.as_str())
            && !mentions(text(&parent_context), &format!("{}/", base(dir)))
        {
            found.push(format!("`{dir}/` is not listed in `{parent_context}`"));
        }
        if files.contains(CONTEXT) && !root_links.contains(&context) {
            found.push(format!(
                "root CONTEXT.md does not link `{context}` in its folder map"
            ));
        }
    }
    found
}

/// Each file must be named in the `CONTEXT.md` of the nearest folder allowed to hold one,
/// by its path relative to that folder.
fn file_problems<'a>(files: &BTreeSet<&str>, text: &impl Fn(&str) -> &'a str) -> Vec<String> {
    let mut found = Vec::new();
    for &file in files.iter().filter(|file| !is_context(file)) {
        let mut dir = parent(file);
        while is_exempt(dir) {
            dir = parent(dir);
        }
        let context = context_of(dir);
        if !files.contains(context.as_str()) {
            continue;
        }
        let name = if dir.is_empty() {
            file
        } else {
            &file[dir.len() + 1..]
        };
        if !mentions(text(&context), name) {
            found.push(format!("`{name}` is not described in `{context}`"));
        }
    }
    found
}

fn link_problems<'a>(
    files: &BTreeSet<&str>,
    dirs: &BTreeSet<&str>,
    text: &impl Fn(&str) -> &'a str,
) -> Vec<String> {
    let mut found = Vec::new();
    for &context in files.iter().filter(|file| is_context(file)) {
        for target in relative_links(text(context)) {
            let exists = resolve(parent(context), without_anchor(target))
                .is_some_and(|p| files.contains(p.as_str()) || dirs.contains(p.as_str()));
            if !exists {
                found.push(format!(
                    "`{context}` links to `{target}`, which does not exist"
                ));
            }
        }
    }
    found
}

/// Destinations of inline Markdown links outside code, without web, mail and
/// same-page links. A destination drops its angle brackets and its title.
fn relative_links(text: &str) -> BTreeSet<&str> {
    let mut targets = BTreeSet::new();
    let mut in_fence = false;
    for line in text.lines() {
        if line.trim_start().starts_with("```") {
            in_fence = !in_fence;
            continue;
        }
        if in_fence {
            continue;
        }
        // Pieces at even positions between backticks are outside inline code.
        for prose in line.split('`').step_by(2) {
            for rest in prose.split("](").skip(1) {
                let Some((inside, _)) = rest.split_once(')') else {
                    continue;
                };
                let target = inside.split_whitespace().next().unwrap_or_default();
                targets.insert(target.trim_start_matches('<').trim_end_matches('>'));
            }
        }
    }
    targets.retain(|target| {
        !(target.contains("://") || target.starts_with('#') || target.starts_with("mailto:"))
    });
    targets
}

fn without_anchor(target: &str) -> &str {
    target.split('#').next().unwrap_or_default()
}

/// `path` relative to `dir`, normalized; `None` when it climbs above the root.
fn resolve(dir: &str, path: &str) -> Option<String> {
    let mut parts: Vec<&str> = dir.split('/').filter(|part| !part.is_empty()).collect();
    for part in path.split('/') {
        match part {
            "" | "." => {}
            ".." => {
                parts.pop()?;
            }
            _ => parts.push(part),
        }
    }
    Some(parts.join("/"))
}

fn rust_problems<'a>(files: &BTreeSet<&str>, text: &impl Fn(&str) -> &'a str) -> Vec<String> {
    files
        .iter()
        .filter(|file| file.ends_with(".rs"))
        .filter(|file| !text(file).trim_start_matches('\u{feff}').starts_with("//!"))
        .map(|file| format!("`{file}` must start with a `//!` comment that says what it does"))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn paths(list: &[&str]) -> Vec<String> {
        list.iter().map(|p| (*p).to_owned()).collect()
    }

    /// A valid repository: root, `src/` and an exempt `font.ufo/`.
    fn valid() -> Tree {
        let files = paths(&[
            "CONTEXT.md",
            "Cargo.toml",
            "src/CONTEXT.md",
            "src/lib.rs",
            "font.ufo/glyphs/a.glif",
        ]);
        let root = format!(
            "# Root\n\n| `Cargo.toml` | manifest |\n| `src/` | [CONTEXT.md](src/CONTEXT.md) |\n\
             | `font.ufo/glyphs/a.glif` | glyph |\n\n{MAP_START}\n{MAP_END}\n"
        );
        let root = with_file_map(&root, &files).unwrap();
        let texts = BTreeMap::from([
            ("CONTEXT.md".to_owned(), root),
            (
                "src/CONTEXT.md".to_owned(),
                "Up: [root](../CONTEXT.md).\n\n| `lib.rs` | code |\n".to_owned(),
            ),
            ("src/lib.rs".to_owned(), "//! Code.\n".to_owned()),
        ]);
        Tree { files, texts }
    }

    fn edit(tree: &mut Tree, path: &str, from: &str, to: &str) {
        let text = tree.texts.get_mut(path).unwrap();
        assert!(text.contains(from), "{path} does not contain {from:?}");
        *text = text.replace(from, to);
    }

    fn add(tree: &mut Tree, path: &str, text: Option<&str>) {
        tree.files.push(path.to_owned());
        if let Some(text) = text {
            tree.texts.insert(path.to_owned(), text.to_owned());
        }
    }

    #[test]
    fn a_valid_tree_has_no_violations() {
        assert_eq!(violations(&valid()), Vec::<String>::new());
    }

    #[test]
    fn a_folder_without_context_is_reported() {
        let mut tree = valid();
        add(&mut tree, "docs/a.md", None);
        edit(
            &mut tree,
            "CONTEXT.md",
            "| `Cargo.toml`",
            "| `docs/a.md` | doc |\n| `Cargo.toml`",
        );
        assert!(
            violations(&tree).contains(&"`docs/` has no CONTEXT.md".to_owned()),
            "{:?}",
            violations(&tree)
        );
    }

    #[test]
    fn ancestors_without_files_still_need_a_context() {
        let mut tree = valid();
        add(&mut tree, "apps/web/CONTEXT.md", Some(""));
        assert!(violations(&tree).contains(&"`apps/` has no CONTEXT.md".to_owned()));
    }

    #[test]
    fn a_context_inside_an_exempt_folder_is_reported() {
        let mut tree = valid();
        add(&mut tree, "font.ufo/CONTEXT.md", Some(""));
        add(
            &mut tree,
            "apps/desktop/src-tauri/capabilities/CONTEXT.md",
            Some(""),
        );
        let found = violations(&tree);
        assert!(
            found.contains(
                &"`font.ufo/CONTEXT.md` must not exist: tools read every file in that folder"
                    .to_owned()
            )
        );
        assert!(found.contains(
            &"`apps/desktop/src-tauri/capabilities/CONTEXT.md` must not exist: tools read every file in that folder"
                .to_owned()
        ));
    }

    #[test]
    fn exemption_matches_whole_path_components() {
        assert!(is_exempt("font.ufo"));
        assert!(is_exempt("tests/font.ufo/glyphs"));
        assert!(is_exempt("apps/desktop/src-tauri/capabilities"));
        assert!(is_exempt("apps/desktop/src-tauri/capabilities/extra"));
        assert!(!is_exempt("apps/desktop/src-tauri/capabilities-old"));
        assert!(!is_exempt("ufo"));
        assert!(!is_exempt(""));
    }

    #[test]
    fn an_undescribed_file_is_reported_against_its_folder() {
        let mut tree = valid();
        add(&mut tree, "src/main.rs", Some("//! Main.\n"));
        assert!(
            violations(&tree)
                .contains(&"`main.rs` is not described in `src/CONTEXT.md`".to_owned())
        );
    }

    #[test]
    fn files_in_exempt_folders_are_described_by_the_nearest_allowed_folder() {
        let mut tree = valid();
        edit(
            &mut tree,
            "CONTEXT.md",
            "| `font.ufo/glyphs/a.glif` | glyph |\n",
            "",
        );
        assert!(
            violations(&tree)
                .contains(&"`font.ufo/glyphs/a.glif` is not described in `CONTEXT.md`".to_owned())
        );
    }

    #[test]
    fn a_name_counts_only_as_a_whole_code_span() {
        let mut tree = valid();
        edit(&mut tree, "src/CONTEXT.md", "`lib.rs`", "`lib.rs.bak`");
        assert!(
            violations(&tree).contains(&"`lib.rs` is not described in `src/CONTEXT.md`".to_owned())
        );
    }

    #[test]
    fn a_subfolder_missing_from_its_parent_is_reported() {
        let mut tree = valid();
        edit(&mut tree, "CONTEXT.md", "| `src/` |", "| src |");
        assert!(violations(&tree).contains(&"`src/` is not listed in `CONTEXT.md`".to_owned()));
    }

    #[test]
    fn a_context_not_linked_from_the_root_is_reported() {
        let mut tree = valid();
        edit(
            &mut tree,
            "CONTEXT.md",
            "[CONTEXT.md](src/CONTEXT.md)",
            "see src",
        );
        assert!(violations(&tree).contains(
            &"root CONTEXT.md does not link `src/CONTEXT.md` in its folder map".to_owned()
        ));
    }

    #[test]
    fn broken_relative_links_are_reported_and_web_links_are_ignored() {
        let mut tree = valid();
        edit(
            &mut tree,
            "src/CONTEXT.md",
            "Up:",
            "[gone](../missing.md) [web](https://example.com/x) [anchor](#top) [dir](../src/) [file](lib.rs#L1) Up:",
        );
        assert_eq!(
            violations(&tree),
            vec!["`src/CONTEXT.md` links to `../missing.md`, which does not exist".to_owned()]
        );
    }

    #[test]
    fn a_link_cannot_climb_above_the_root() {
        let mut tree = valid();
        edit(
            &mut tree,
            "src/CONTEXT.md",
            "Up:",
            "[out](../../x/CONTEXT.md) Up:",
        );
        assert_eq!(
            violations(&tree),
            vec!["`src/CONTEXT.md` links to `../../x/CONTEXT.md`, which does not exist".to_owned()]
        );
    }

    #[test]
    fn a_rust_file_without_a_module_comment_is_reported() {
        let mut tree = valid();
        edit(&mut tree, "src/lib.rs", "//! Code.", "// Code.");
        assert_eq!(
            violations(&tree),
            vec!["`src/lib.rs` must start with a `//!` comment that says what it does".to_owned()]
        );
    }

    #[test]
    fn a_stale_file_map_is_reported() {
        let mut tree = valid();
        edit(&mut tree, "CONTEXT.md", "Cargo.toml\n", "Cargo.lock\n");
        assert_eq!(
            violations(&tree),
            vec![
                "the file map in CONTEXT.md is out of date: run `cargo xtask context update`"
                    .to_owned()
            ]
        );
    }

    #[test]
    fn missing_markers_are_reported() {
        let mut tree = valid();
        edit(&mut tree, "CONTEXT.md", MAP_END, "");
        assert_eq!(
            violations(&tree),
            vec![format!(
                "CONTEXT.md has no file map between `{MAP_START}` and `{MAP_END}`"
            )]
        );
    }

    #[test]
    fn with_file_map_replaces_only_the_block() {
        let text = format!("before\n{MAP_START}\nold\n{MAP_END}\nafter\n");
        let updated = with_file_map(&text, &paths(&["a.txt"])).unwrap();
        assert_eq!(
            updated,
            format!("before\n{MAP_START}\n```text\n.\n└── a.txt\n```\n{MAP_END}\nafter\n")
        );
        assert_eq!(
            with_file_map(&updated, &paths(&["a.txt"])).unwrap(),
            updated
        );
    }

    #[test]
    fn with_file_map_needs_both_markers_in_order() {
        let swapped = format!("{MAP_END}\n{MAP_START}\n");
        assert!(with_file_map(&swapped, &[]).is_err());
        assert!(with_file_map("no markers", &[]).is_err());
    }

    #[test]
    fn an_undescribed_root_file_is_reported_against_the_root() {
        let mut tree = valid();
        add(&mut tree, "README.md", None);
        assert!(
            violations(&tree).contains(&"`README.md` is not described in `CONTEXT.md`".to_owned())
        );
    }

    #[test]
    fn link_titles_angle_brackets_and_code_are_understood() {
        let mut tree = valid();
        edit(
            &mut tree,
            "src/CONTEXT.md",
            "Up:",
            "[t](lib.rs \"title\") [a](<lib.rs>) `[c](gone.md)`\n```\n[f](gone.md)\n```\nUp:",
        );
        assert_eq!(violations(&tree), Vec::<String>::new());
    }

    #[test]
    fn a_broken_link_is_reported_once_per_file() {
        let mut tree = valid();
        edit(
            &mut tree,
            "src/CONTEXT.md",
            "Up:",
            "[a](gone.md) [b](gone.md) Up:",
        );
        assert_eq!(
            violations(&tree),
            vec!["`src/CONTEXT.md` links to `gone.md`, which does not exist".to_owned()]
        );
    }

    #[test]
    fn the_root_may_link_a_context_through_any_equivalent_path() {
        let mut tree = valid();
        edit(
            &mut tree,
            "CONTEXT.md",
            "[CONTEXT.md](src/CONTEXT.md)",
            "[CONTEXT.md](./src/CONTEXT.md#top)",
        );
        assert_eq!(violations(&tree), Vec::<String>::new());
    }

    #[test]
    fn an_end_marker_quoted_before_the_map_is_ignored() {
        let text = format!("see `{MAP_END}`\n{MAP_START}\nold\n{MAP_END}\n");
        let updated = with_file_map(&text, &paths(&["a.txt"])).unwrap();
        assert!(updated.starts_with(&format!("see `{MAP_END}`\n{MAP_START}\n```text\n")));
    }

    #[test]
    fn a_rust_file_may_start_with_a_byte_order_mark() {
        let mut tree = valid();
        edit(&mut tree, "src/lib.rs", "//! Code.", "\u{feff}//! Code.");
        assert_eq!(violations(&tree), Vec::<String>::new());
    }

    #[test]
    fn is_context_matches_the_whole_file_name() {
        assert!(is_context("CONTEXT.md"));
        assert!(is_context("docs/CONTEXT.md"));
        assert!(!is_context("docs/NOTCONTEXT.md"));
    }

    #[test]
    fn render_keeps_a_folder_with_one_subfolder_and_one_file_open() {
        let expected = ".\n└── a/\n    ├── b/c.txt\n    └── d.txt\n";
        assert_eq!(render(&paths(&["a/b/c.txt", "a/d.txt"])), expected);
    }

    #[test]
    fn render_leaves_out_folders_that_hold_only_a_context() {
        assert_eq!(render(&paths(&["x/CONTEXT.md", "y.txt"])), ".\n└── y.txt\n");
    }

    #[test]
    fn render_lists_folders_first_and_joins_single_child_chains() {
        let files = paths(&[
            "README.md",
            "CONTEXT.md",
            ".cargo/config.toml",
            ".cargo/CONTEXT.md",
            "apps/desktop/package.json",
            "apps/desktop/src/main.tsx",
            "apps/desktop/src/App.tsx",
            "docs/adr/0001.md",
            "docs/plan.md",
        ]);
        let expected = "\
.
├── .cargo/config.toml
├── apps/desktop/
│   ├── src/
│   │   ├── App.tsx
│   │   └── main.tsx
│   └── package.json
├── docs/
│   ├── adr/0001.md
│   └── plan.md
└── README.md
";
        assert_eq!(render(&files), expected);
    }
}
